# Taken from AuthMe's repo
# MIT
name: Release

# On changes to release branches
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 17
          distribution: zulu

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: 🐘 Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: 📦 Build Artifacts
        run: ./gradlew build

      - name: ☁ Upload artifacts to cloud
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: "versions/*/build/libs/*.jar"

      - name: ☁ Upload 1.18.2 artifacts to cloud
        uses: actions/upload-artifact@v3
        with:
          name: "1.18.2 Artifacts"
          path: "versions/1.18.2-fabric/build/libs/*.jar"

      - name: ☁ Upload 1.19.2 artifacts to cloud
        uses: actions/upload-artifact@v3
        with:
          name: "1.19.2 Artifacts"
          path: "versions/1.19.2-fabric/build/libs/*.jar"

      - name: ☁ Upload 1.19.2 artifacts to cloud
        uses: actions/upload-artifact@v3
        with:
          name: "1.19.3 Artifacts"
          path: "versions/1.19.3-fabric/build/libs/*.jar"

  mod_release:
    name: Publish to repos
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        minecraft_version: ["1.18.2", "1.19.2", "1.19.3"]

    steps:
      - name: ✨ Checkout repository
        uses: actions/checkout@v3

      - name: ☁ Download artifacts from cloud
        uses: actions/download-artifact@v3
        with:
          name: "${{ matrix.minecraft_version }} Artifacts"
          path: build

      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: 📦 Upload artifacts to mod hosts
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          curseforge-id: 754889
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          modrinth-id: E6BMMeJm
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}

          github-tag: ${{ steps.get_release.outputs.tag_name }}
          github-draft: false
          github-prerelease: false

          name: "Tubion ${{ steps.get_release.outputs.tag_name }} for Minecraft ${{ matrix.minecraft_version }}"
          version: "${{ steps.get_release.outputs.tag_name }}-${{ matrix.minecraft_version }}"
          version-type: release
          files-primary: "build/!(*-@(dev|sources|javadoc)).jar"
          files-secondary: "build/*-@(dev|sources|javadoc).jar"
          changelog-file: "CHANGELOG.md"

          loaders: fabric
          game-versions: "${{ matrix.minecraft_version }}"
          java: "17"